# Generated by Django 5.0.10 on 2024-12-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Musteri",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("isim", models.CharField(max_length=100)),
                ("soyisim", models.CharField(max_length=100)),
                ("telefon", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("dogum_tarihi", models.DateField()),
                (
                    "cinsiyet",
                    models.BooleanField(choices=[(True, "Erkek"), (False, "Kadın")]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ucus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("kalıs", models.CharField(max_length=100)),
                ("varıs", models.CharField(max_length=100)),
                ("kalkis_saati", models.TimeField()),
                ("varis_saati", models.TimeField()),
                ("toplam_sure", models.CharField(max_length=50)),
                ("ucak_tipi", models.CharField(max_length=100)),
                ("eco_fly_fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "business_fly_fiyat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "first_class_fly_fiyat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bilet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bilet_no", models.CharField(max_length=100, unique=True)),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("koltuk", models.CharField(max_length=5)),
                ("tarih", models.TimeField()),
                (
                    "musteri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biletler",
                        to="wbst.musteri",
                    ),
                ),
                (
                    "ucus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biletler",
                        to="wbst.ucus",
                    ),
                ),
            ],
        ),
    ]
