# Generated by Django 5.0.10 on 2024-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbst", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bilet",
            old_name="id",
            new_name="bilet_id",
        ),
        migrations.RenameField(
            model_name="musteri",
            old_name="id",
            new_name="musteri_id",
        ),
        migrations.RenameField(
            model_name="ucus",
            old_name="business_fly_fiyat",
            new_name="fiyat",
        ),
        migrations.RenameField(
            model_name="ucus",
            old_name="id",
            new_name="ucus_id",
        ),
        migrations.RemoveField(
            model_name="bilet",
            name="musteri",
        ),
        migrations.RemoveField(
            model_name="ucus",
            name="eco_fly_fiyat",
        ),
        migrations.RemoveField(
            model_name="ucus",
            name="first_class_fly_fiyat",
        ),
        migrations.RemoveField(
            model_name="ucus",
            name="varis_saati",
        ),
        migrations.AlterField(
            model_name="ucus",
            name="kalkis_saati",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ucus",
            name="toplam_sure",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="ucus",
            name="ucak_tipi",
            field=models.CharField(max_length=50),
        ),
    ]
