# Generated by Django 5.0.10 on 2024-12-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbst", "0003_alter_musteri_email_odeme"),
    ]

    operations = [
        migrations.AddField(
            model_name="bilet",
            name="musteri",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biletler",
                to="wbst.musteri",
            ),
        ),
    ]
