# Generated by Django 5.0.10 on 2024-12-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbst", "0004_bilet_musteri"),
    ]

    operations = [
        migrations.AddField(
            model_name="bilet",
            name="durum",
            field=models.CharField(
                choices=[
                    ("Beklemede", "Beklemede"),
                    ("Ödendi", "Ödendi"),
                    ("İptal", "İptal"),
                ],
                default="Beklemede",
                max_length=20,
            ),
        ),
    ]
